In [1]:
import pandas as pd

In [8]:
df = pd.read_csv('../Datasets/TMDb_updated.csv')
df.head()

,Unnamed: 0,title,overview,original_language,vote_count,vote_average
0,0,Ad Astra,"The near future, a time when both hope and har...",en,2853,5.9
1,1,Bloodshot,"After he and his wife are murdered, marine Ray...",en,1349,7.2
2,2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,en,2530,7.1
3,3,Ant-Man,Armed with the astonishing ability to shrink i...,en,13611,7.1
4,4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",en,3542,5.9

In [9]:
new_df = df[['title','overview','vote_average']]

new_df

,title,overview,vote_average
0,Ad Astra,"The near future, a time when both hope and har...",5.9
1,Bloodshot,"After he and his wife are murdered, marine Ray...",7.2
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,7.1
3,Ant-Man,Armed with the astonishing ability to shrink i...,7.1
4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",5.9
...,...,...,...
9995,Cargo,The story of CARGO takes place on rusty space-...,5.9
9996,The Good Night,"Gary, a musician, is trapped in an unhappy rel...",5.6
9997,The World Is Yours,"To escape his life of crime, a Paris drug deal...",7.1
9998,The Grand Seduction,A small fishing village must procure a local d...,6.7
9999,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...",6.7

In [10]:
new_df['title_for_join']=new_df['title'].str.strip()
new_df['title_for_join']=new_df['title_for_join'].str.replace(" ",'')
new_df['title_for_join']=new_df['title_for_join'].str.lower()

<ipython-input-10-73f2a961771f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title_for_join']=new_df['title'].str.strip()
<ipython-input-10-73f2a961771f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title_for_join']=new_df['title_for_join'].str.replace(" ",'')
<ipython-input-10-73f2a961771f>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title_for_join']=new_df['title_for_join'].str.lower()

In [11]:
new_df.sample(20)

,title,overview,vote_average,title_for_join
2364,In the Bedroom,"Summertime on the coast of Maine, ""In the Bedr...",6.8,inthebedroom
2140,Austin Powers: International Man of Mystery,As a swingin' fashion photographer by day and ...,6.5,austinpowers:internationalmanofmystery
9516,Destination Wedding,Ellie Hamilton is helping plan her little sist...,6.7,destinationwedding
4503,True Crime,"Boozer, skirt chaser, careless father. You cou...",6.5,truecrime
1034,Commando,"John Matrix, the former leader of a special co...",6.6,commando
8414,The Full Monty,"Sheffield, England. Gaz, a jobless steelworker...",7.0,thefullmonty
6736,Julie & Julia,Julia Child and Julie Powell â€“ both of whom wr...,6.6,julie&julia
3107,The Haunting in Connecticut,When the Campbell family moves to upstate Conn...,6.1,thehauntinginconnecticut
5941,The Lion Guard: Return of the Roar,"Set in the African savannah, the film follows ...",6.0,thelionguard:returnoftheroar
7514,Bedknobs and Broomsticks,Three children evacuated from London during Wo...,7.0,bedknobsandbroomsticks
2816,Midnight Cowboy,Joe Buck is a wide-eyed hustler from Texas hop...,7.6,midnightcowboy
5276,The Patriot,A deadly virus threatens to wipe out an entire...,4.5,thepatriot
8376,The Disappearance of Haruhi Suzumiya,"It is mid-december, and SOS Brigade chief Haru...",7.9,thedisappearanceofharuhisuzumiya
2739,Tarzan & Jane,"Sprightly amusement for kids of all ages, Disn...",5.8,tarzan&jane
9486,Surveillance,An FBI agent tracks a serial killer with the h...,6.0,surveillance
9359,Coal Miner's Daughter,"Biography of Loretta Lynn, a country and weste...",7.2,coalminer'sdaughter
3575,Rab Ne Bana Di Jodi,"A lonely 40-ish man, likely to remain a bachel...",6.7,rabnebanadijodi
9684,Firebreather,Firebreather is a CGI animated made-for-TV fil...,6.4,firebreather
9439,Gentlemen of Fortune,A kindergarten director Troshkin is a dead rin...,7.8,gentlemenoffortune
5738,Shaolin,China is plunged into strife as feuding warlor...,6.6,shaolin

In [12]:
chars = "\`*_{}[]()>#+-.,!$:;%'&/?"
for c in chars:
    new_df['title_for_join'] = new_df['title_for_join'].str.replace(c,"")

new_df

<ipython-input-12-7bb9c5993776>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['title_for_join'] = new_df['title_for_join'].str.replace(c,"")

,title,overview,vote_average,title_for_join
0,Ad Astra,"The near future, a time when both hope and har...",5.9,adastra
1,Bloodshot,"After he and his wife are murdered, marine Ray...",7.2,bloodshot
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,7.1,badboysforlife
3,Ant-Man,Armed with the astonishing ability to shrink i...,7.1,antman
4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",5.9,percyjacksonseaofmonsters
...,...,...,...,...
9995,Cargo,The story of CARGO takes place on rusty space-...,5.9,cargo
9996,The Good Night,"Gary, a musician, is trapped in an unhappy rel...",5.6,thegoodnight
9997,The World Is Yours,"To escape his life of crime, a Paris drug deal...",7.1,theworldisyours
9998,The Grand Seduction,A small fishing village must procure a local d...,6.7,thegrandseduction
9999,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...",6.7,woochithedemonslayer

In [13]:
clean_df = new_df.drop_duplicates()
clean_df

,title,overview,vote_average,title_for_join
0,Ad Astra,"The near future, a time when both hope and har...",5.9,adastra
1,Bloodshot,"After he and his wife are murdered, marine Ray...",7.2,bloodshot
2,Bad Boys for Life,Marcus and Mike are forced to confront new thr...,7.1,badboysforlife
3,Ant-Man,Armed with the astonishing ability to shrink i...,7.1,antman
4,Percy Jackson: Sea of Monsters,"In their quest to confront the ultimate evil, ...",5.9,percyjacksonseaofmonsters
...,...,...,...,...
9995,Cargo,The story of CARGO takes place on rusty space-...,5.9,cargo
9996,The Good Night,"Gary, a musician, is trapped in an unhappy rel...",5.6,thegoodnight
9997,The World Is Yours,"To escape his life of crime, a Paris drug deal...",7.1,theworldisyours
9998,The Grand Seduction,A small fishing village must procure a local d...,6.7,thegrandseduction
9999,Woochi: The Demon Slayer,"Spanning four centuries in Korea, this epic ac...",6.7,woochithedemonslayer

In [15]:
clean_df.to_csv(r'../clean_datasets/clean_TMDb_data.csv', index = False)